### ISSUE TITLE
How do we use this codes for getting the output for our datasets

### ISSUE THREAD

**Issue by Uma1699** [dormon/3DApps#1]
I have followed all the steps you mentioned  for building. All the seven steps you mentioned works fine for me, including make. However, I am unable to use it for getting the outputs for my input videos. Could you kindly provide us with a guide to how and where to give inputs and get outputs, and in what formats.

**Comment by dormon** [comment]
Hello, which application would you like to use?
There are several sub-applications in 3DApps

**Comment by Uma1699** [comment]
I would like to use the application of quilt detection in video sequences

**Comment by ichlubna** [comment]
> how and where to give inputs and get outputs,

I am sorry for the inconvenience. There was a problem with the output log since the code was adjusted to conduct the experiments.  0956e43ca944127795eb399937446a7d9ce81b64 should be working fine now. 
A simple example is:
`./quiltDetector -i /path/to/video.mkv -o /working/dir/ -y 2 `
Where -y is a vertical motion tolerance. 
Adding -e exports the frames into directories in the working directory.
The result of the detection is available in stdout showing what sequences were detected.

**Comment by ghost** [comment]
Hello, I am also facing similar problem. After executing all the steps provided in the readme, the executable file quiltDetector is not present in the build directory. Can you please guide me in finding/generating the quiltDetector?

**Comment by ichlubna** [comment]
@khaidem2020 Hello, are you sure that the build process didn't fail? Please check the output or logs. It should be possible to set only the quiltDetector to be compiled in ccmake or the CMake GUI to avoid unnecessary compilations and other dependency problems. You can also use the makefile like:
`make quiltDetector`
to compile just the app.

**Comment by sKhaidem** [comment]
> @khaidem2020 Hello, are you sure that the build process didn't fail? Please check the output or logs. It should be possible to set only the quiltDetector to be compiled in ccmake or the CMake GUI to avoid unnecessary compilations and other dependency problems. You can also use the makefile like: `make quiltDetector` to compile just the app.

Hi @ichlubna, I have tried to build separately the app `quiltDetector` from the list of 3DApps but to no avail. I tried to compile the `quiltDetector.cpp` but the were some header files missing. Will you be kind enough to provide the successfully built `quiltDetector` and it's necessary components? It will be very helpful. Thank you.

**Comment by ichlubna** [comment]
> @sKhaidem Will you be kind enough to provide the successfully built quiltDetector and it's necessary components?

I am sorry for the delay @khaidem2020. [Here](https://drive.google.com/file/d/1FDaAkE8bonysXODh2XuqXb26E9Um8hKR/view?usp=sharing ) is an Ubuntu 20 64-bit build with all the necessary libraries and two examples with data. Might be also relevant to @Uma1699 but I think he managed to run the app after all. We have tested this binary on three Ubuntu machines so we hope that this will help you run the application without any problems.

**Comment by sKhaidem** [comment]
> 

@ichlubna Thank you for providing the application and its necessary libraries.
